"""
Generates storage-api.md - a cheap-to-read index of everything storage.js exports.

storage.js is ~4,900 lines / ~62k tokens. Reading it whole to find out what is in it is
the single most expensive habit in this repo (see CLAUDE.md, "Reading big files"). This
script turns it into a ~3k-token map: every export, grouped under the section banners that
already live in the file, with its line number.

Unlike gen_docs.py, this PARSES the source - it cannot drift. Re-run it after any change to
storage.js:

    set PYTHONDONTWRITEBYTECODE=1
    python code/gen_storage_api.py

PYTHONDONTWRITEBYTECODE is required: a __pycache__ directory inside code/ breaks Chrome's
"Load unpacked" (underscore-reserved name).
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "storage.js")
OUTPUT = os.path.join(HERE, "storage-api.md")

BANNER_PREFIX = "// ---"
KINDS = ("function", "const", "let", "var", "class")


def split_params(text):
    """Return the parameter list of a function declaration, balanced-paren aware."""
    start = text.find("(")
    if start == -1:
        return ""
    depth = 0
    for i in range(start, len(text)):
        ch = text[i]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    return text[start:] + "..."


def describe_const(rest):
    """Best-effort one-word shape for a non-function export."""
    if "=>" in rest:
        return "arrow fn"
    after = rest.split("=", 1)[1].strip() if "=" in rest else ""
    if after.startswith("["):
        return "array"
    if after.startswith("{"):
        return "object"
    if after.startswith(("'", '"', "`")):
        return "string"
    if after.startswith(("new Map", "new Set")):
        return after.split("(")[0].strip()
    return "value"


def parse(path):
    """-> list of (section_title, [(line_no, name, signature, kind), ...])"""
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().split("\n")

    sections = []
    current = ("(top of file)", [])
    pending_banner = False

    for idx, raw in enumerate(lines, start=1):
        if raw.startswith(BANNER_PREFIX):
            pending_banner = True
            continue
        if pending_banner and raw.startswith("// "):
            if current[1] or current[0] != "(top of file)":
                sections.append(current)
            current = (raw[3:].strip(), [])
            pending_banner = False
            continue
        pending_banner = False

        if not raw.startswith("export "):
            continue
        rest = raw[len("export ") :].strip()
        is_async = rest.startswith("async ")
        if is_async:
            rest = rest[len("async ") :].strip()

        kind = next((k for k in KINDS if rest.startswith(k + " ")), None)
        if kind is None:
            continue
        rest = rest[len(kind) + 1 :].strip()
        name = ""
        for ch in rest:
            if ch.isalnum() or ch in "_$":
                name += ch
            else:
                break
        if not name:
            continue

        if kind == "function":
            sig = name + split_params(rest)
            if is_async:
                sig = "async " + sig
        elif kind == "class":
            sig = "class " + name
        else:
            sig = name + "  (" + describe_const(rest) + ")"
        current[1].append((idx, name, sig, kind))

    sections.append(current)
    return [s for s in sections if s[1]]


def render(sections, source_lines, source_name):
    total = sum(len(items) for _, items in sections)
    out = []
    out.append("# storage.js - export index")
    out.append("")
    out.append(
        "Generated by `code/gen_storage_api.py` - do not edit by hand. "
        "Re-run it after any change to `storage.js`."
    )
    out.append("")
    out.append(
        "`storage.js` is **{:,} lines** and holds **{} exports** across {} sections. "
        "Read this file instead of the source to find what you need, then read only "
        "that span.".format(source_lines, total, len(sections))
    )
    out.append("")
    out.append("## Sections")
    out.append("")
    for title, items in sections:
        out.append(
            "- [{}](#{}) - {} exports, from line {}".format(
                title,
                title.lower()
                .replace(" ", "-")
                .replace(",", "")
                .replace("/", "")
                .replace("&", "")
                .replace(".", ""),
                len(items),
                items[0][0],
            )
        )
    out.append("")
    for title, items in sections:
        out.append("## " + title)
        out.append("")
        out.append("| Line | Export |")
        out.append("|---:|---|")
        for line_no, _name, sig, _kind in items:
            out.append("| {} | `{}` |".format(line_no, sig))
        out.append("")
    return "\n".join(out) + "\n"


def main():
    if not os.path.exists(SOURCE):
        sys.exit("storage.js not found at " + SOURCE)
    with open(SOURCE, encoding="utf-8") as fh:
        source_lines = len(fh.read().split("\n"))
    sections = parse(SOURCE)
    if not sections:
        sys.exit("No exports found - has storage.js changed shape?")
    text = render(sections, source_lines, os.path.basename(SOURCE))
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    total = sum(len(items) for _, items in sections)
    print("Wrote {} - {} exports in {} sections".format(OUTPUT, total, len(sections)))
    print("   source: {:,} lines   index: {:,} bytes".format(source_lines, len(text)))


if __name__ == "__main__":
    main()
