// GENERATED by gen_template.py from sheet_contract.py - do not edit by hand.
export const IMPORT_COLUMNS = {
  "Companies": {
    "mandatory": [
      "Company_ID",
      "Universe_Order",
      "Company",
      "Evidence_Coverage",
      "Priority",
      "Research_Status",
      "Evidence_Status",
      "Excluded"
    ],
    "optional": [
      "Industry",
      "Use_Case_Fit_Score",
      "Priority_Score",
      "Research_Quality",
      "Priority_Rationale",
      "Primary_Source_URL",
      "Last_Verified",
      "Portfolio_Profile",
      "Portfolio_Profile_Confidence",
      "Registry_Official_Name",
      "Registry_ID",
      "Registry_Address",
      "Alternative Company Name",
      "LinkedIn Link",
      "Prospect_Status",
      "Company_Type",
      "Target_Country_Relationship",
      "Global_HQ_City",
      "Global_HQ_Country",
      "Main_Home_Location",
      "Home_Decision_Authority",
      "Global_Revenue",
      "Revenue_Currency",
      "Revenue_Period",
      "Global_Revenue_Confidence",
      "Home_Revenue",
      "Home_Revenue_Currency",
      "Home_Revenue_Period",
      "Home_Revenue_Confidence",
      "Global_Employees",
      "Global_Employees_Period",
      "Global_Employees_Confidence",
      "Home_Employees",
      "Home_Employees_Period",
      "Home_Employees_Confidence",
      "Investment_Global",
      "Investment_Home",
      "Investment_Confidence",
      "Top_Initiatives",
      "Relevant_Contacts_Count",
      "Home_Size_Fit_Score",
      "Decision_Authority_Score",
      "Maturity_Fit_Score",
      "Investment_Score",
      "Contact_Access_Score",
      "Size_Bucket",
      "Employee_Count",
      "Employee_Range",
      "Size_Source",
      "Size_Scope",
      "Size_Confidence",
      "Size_Last_Verified"
    ]
  },
  "Contacts": {
    "mandatory": [
      "Contact_ID",
      "Company_ID",
      "Company",
      "Full_Name",
      "Job_Title"
    ],
    "optional": [
      "Function",
      "Seniority",
      "Relevance",
      "Home_Based",
      "City",
      "Country",
      "Public_Business_Email",
      "Profile_URL",
      "Last_Verified",
      "Evidence_Quality"
    ]
  },
  "Initiatives": {
    "mandatory": [
      "Initiative_ID",
      "Company_ID",
      "Company",
      "Initiative_Name"
    ],
    "optional": [
      "Category",
      "Scope",
      "Business_Function",
      "Description",
      "Status",
      "Announced_Date",
      "Investment_Amount",
      "Currency",
      "Technology_or_Partner",
      "Source_URL",
      "Last_Verified",
      "Evidence_Quality"
    ]
  },
  "Investment": {
    "mandatory": [
      "Investment_ID",
      "Company_ID",
      "Company"
    ],
    "optional": [
      "Year",
      "Scope",
      "Amount_Low",
      "Amount_High",
      "Currency",
      "Evidence_Type",
      "Basis",
      "Source_URL",
      "Last_Verified"
    ]
  },
  "Sources": {
    "mandatory": [
      "Source_ID"
    ],
    "optional": [
      "Company_ID",
      "Company_or_Coverage",
      "Source_Type",
      "Source_Title",
      "Source_Date",
      "URL",
      "Used_For",
      "Evidence_Quality",
      "Last_Verified"
    ]
  },
  "Exclusion_List": {
    "mandatory": [
      "Company_ID",
      "Company",
      "Exclusion_Reason"
    ],
    "optional": []
  },
  "Aliases": {
    "mandatory": [
      "Company_ID",
      "Canonical_Name",
      "Alias",
      "Alias_Type",
      "Search_Priority",
      "Normalized_Alias"
    ],
    "optional": [
      "Language",
      "Source_or_Notes",
      "Source_URL",
      "Verification_Status"
    ]
  }
};
